In [1]:
import torch

In [3]:
torch.tensor([1,2,3])
torch.tensor([[1,2,3],[4,5,6]])
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float64)
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.int32)
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.int64)


tensor([[1, 2, 3],
        [4, 5, 6]])

In [4]:
torch.ones(2,3,dtype=torch.float32)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.trace(torch.ones(2,3))

tensor(2.)

In [6]:
torch.cat((torch.ones(2,3),torch.ones(2,3)),dim=1)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])